version: '3.0'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/mhm-stack/portainer:/data
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - ${MOSQUITTO_PORT1}:1883
      - ${MOSQUITTO_PORT2}:9001 
    environment:
    - TZ=Pacific/Auckland
    restart: always
    volumes:
      - /opt/mhm-stack/mosquitto_data:/mosquitto/data
      - /opt/mhm-stack/mosquitto_data:/mosquitto/log
      - /opt/mhm-stack/mosquitto_data/config:/mosquitto/config
    restart: unless-stopped
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Pacific/Auckland
    ports:
      - "1880:1880"
    volumes:
      - /opt/mhm-stack/node-red-data:/data
    restart: unless-stopped
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - /opt/mhm-stack/influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    restart: unless-stopped   
  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    restart: unless-stopped     
  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - /opt/mhm-stack/grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped
#  frigate:
#    container_name: frigate
#    image: blakeblackshear/frigate:stable-amd64
#    restart: always
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - /opt/mhm-stack/frigate-data/config.yml:/config/config.yml
#    ports:
#      - ${frigate1_PORT}:5000
#      - ${frigate2_PORT}:1935
#    environment:
#      FRIGATE_RTSP_PASSWORD: "${MHM_frigate_PASSWORD}" 
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - /opt/mhm-stack/duplicati/config:/config
      - /opt:/source
    ports:
      - 8200:8200
    restart: unless-stopped