version: '3.0'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/mhm-stack/portainer:/data
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/mhm-stack/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
 #   devices:
 #    -   /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host    
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - ${MOSQUITTO_PORT1}:1883
      - ${MOSQUITTO_PORT2}:9001 
    environment:
    - TZ=Pacific/Auckland
    restart: always
    volumes:
      - /opt/mhm-stack/mosquitto_data:/mosquitto/data
      - /opt/mhm-stack/mosquitto_data:/mosquitto/log
      - /opt/mhm-stack/mosquitto_data/config:/mosquitto/config
    restart: unless-stopped
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Pacific/Auckland
    ports:
      - "1880:1880"
    volumes:
      - /opt/mhm-stack/node-red-data:/data
    restart: unless-stopped
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - /opt/mhm-stack/influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    restart: unless-stopped
  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    restart: unless-stopped     
#  grafana:
#    image: grafana/grafana-oss:8.4.3
#    volumes:
#      - /opt/mhm-stack/grafana-storage:/var/lib/grafana:rw
#    depends_on:
#      - influxdb
#    ports:
#      - ${GRAFANA_PORT}:3000
#    restart: unless-stopped
  tasmoadmin:
    image: raymondmm/tasmoadmin
    ports:
      - ${tasmoadmin_PORT}:80
    volumes:
      - /opt/mhm-stack/tasmoadmin_data:/data
    restart: always
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
      PUID: 1000
      PGID: 1000
    volumes:
     - /opt/mhm-stack/mariadb:/config
    ports:
      - ${mariadb_PORT}:3306  
    restart: unless-stopped
    
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/mhm-stack/frigate-data/config.yml:/config/config.yml
    ports:
      - ${frigate1_PORT}:5000
      - ${frigate2_PORT}:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "${HA_frigate_PASSWORD}" 
#  tailscale:
#        container_name: tailscale
#        volumes:
#            - /opt/mhm-stack/tailscale/var/lib:/var/lib'
#            - /opt/mhm-stack/tailscale/dev/net/tun:/dev/net/tun'
#        network_mode: host
#        privileged: true
#        image: tailscale/tailscale
#        entrypoint: tailscaled 
#        restart: unless-stopped
#  adguardhome:
#    image: adguard/adguardhome
#    container_name: adguardhome
#    ports:
#      - 784:784/udp
#      - 853:853/tcp
#      - 80:80/tcp
#      - 443:443/tcp
#    volumes:
#      - /opt/mhm-stack/adguard:/opt/adguardhome/work
#      - /opt/mhm-stack/adguard:/opt/adguardhome/conf
#    restart: unless-stopped
  esphome:
        container_name: esphome
        image: esphome/esphome
        volumes:
            - /opt/mhm-stack/esphome/:/config:rw
            # Use local time for logging timestamps
            #- /etc/localtime:/etc/localtime:ro
        restart: always
        privileged: true
        network_mode: host
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - /opt/mhm-stack/duplicati/config>:/config
      - /opt:/source
    ports:
      - 8200:8200
    restart: unless-stopped
#  firefox:
#    ports:
#        - '6911:6901' #change 6901 as necessary. eg. '6901:6901', '6902:6901', '6903:6901'
#    environment:
#        - VNC_PW=password #change as desired
#    shm_size: '512m' #change per your needs. eg. '512m', '1gb', '2gb'
#    image: 'kasmweb/firefox:1.9.0' #change the image to your desired image    
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - TZ=Europe/London
      - DOCKER_HUB_USERNAME=USER #optional
      - DOCKER_HUB_PASSWORD=PASS #optional
    volumes:
      - /opt/mhm-stack/kasm:/opt
      #- /path/to/profiles:/profiles #optional
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped    